chore(ci): revert the commit for formatter

diff --git a/.github/workflows/ci-main.yml b/.github/workflows/ci-main.yml
--- a/.github/workflows/ci-main.yml
+++ b/.github/workflows/ci-main.yml
@@ -2,11 +2,73 @@ name: CI for main
 
 on:
   push:
-    branches: [ feat-ci ]
+    branches: [ main ]
   pull_request:
-    branches: [ feat-ci ]
+    branches: [ main ]
 
 jobs:
+  checking-code-format:
+    name: check code format with clang-format
+    runs-on: ubuntu-22.04
+    strategy:
+      matrix:
+        path:
+          - check: 'module'
+            exclude: '(stelaLowparser|stelaLowscanner|lowparser|lowscanner)'
+    steps:
+    - name: checkout repository codes
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
+
+    - name: cache APT packages
+      uses: actions/cache@v4
+      with:
+        path: /var/cache/apt
+        key: ${{ runner.os }}-apt-${{ hashFiles('/var/lib/apt/lists/lock') }}
+        restore-keys: |
+          ${{ runner.os }}-apt-
+
+    - name: cache Docker packages
+      uses: actions/cache@v4
+      with:
+        path: |
+          /var/cache/apt/archives
+          /etc/apt/keyrings/docker.asc
+        key: ${{ runner.os }}-docker-packages
+        restore-keys: |
+          ${{ runner.os }}-docker-
+
+    - name: install native dependencies
+      run: |
+        sudo apt update
+        sudo apt-get install ca-certificates curl
+        sudo install -m 0755 -d /etc/apt/keyrings
+        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+        sudo chmod a+r /etc/apt/keyrings/docker.asc
+
+        echo \
+          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
+          $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
+          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+        sudo apt-get update
+        
+        sudo apt-get install python3 docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+
+    - name: run formatter 
+      run: |
+        cd ${{github.workspace}} 
+        python3 build/builder.py format docker
+
+    - name: check if there is a style violiations 
+      run: |
+        git diff > output.txt
+        if [ -s output.txt ]; then
+          echo "error: some codes violates our code style."
+          cat output.txt
+          exit 1
+        fi
+
   build-on-linux:
     name: build on linux
     runs-on: ubuntu-22.04
@@ -222,7 +284,7 @@ jobs:
         path: ${{github.workspace}}\bin\Release\*.dll
 
   publish-doc:
-    needs: [build-on-linux, build-on-macos, build-on-windows]
+    needs: [checking-code-format, build-on-linux, build-on-macos, build-on-windows]
     name: publish doc
     runs-on: ubuntu-22.04
 
